services:
  postgres:
    image: postgres:16-alpine
    container_name: gophprofile-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gopher
      POSTGRES_PASSWORD: gopher123
      POSTGRES_DB: gophprofile
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gopher -d gophprofile"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z  # стабильный релиз  
    container_name: gophprofile-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: gophprofile-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: gopher
      RABBITMQ_DEFAULT_PASS: gopher123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data:
